version: 0.2

phases:
  install:
    runtime-versions:
      java: latest
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on %date
      - zip source-bundle.zip mps-payment-web/target/mps-payment-web-1.0-SNAPSHOT.jar
artifacts:
  files:
    - mps-payment-web/target/mps-payment-web-1.0-SNAPSHOT.jar
    - mps-payment-worker/target/mps-payment-worker-1.0-SNAPSHOT.jar
